### PR TITLE
added BaseType property to ContextualType

### PR DESCRIPTION
**Pull request by adamjones1**
eg. this (for #46)

### CODE REVIEW

**Comment by RicoSuter** [comment]
Is this actually working as expected? Can you add some tests?

**Comment by RicoSuter** [comment]
Added a test - looks good so far.. Any other things to add to this PR? Or can we merge?

**Comment by adamjones1** [comment]
It works ok for me! I can't think of anything further to add.

**Comment by RicoSuter** [comment]
v1.0.13

**Pull request merged**
