### PR TITLE
Fix NRT reflection for nested types

### PR DESCRIPTION
**Pull request by ProductiveRage**
This test fails to further illustrate the problem that I'm encountering in issue #24 with the "EnsureValidNullability" method

### CODE REVIEW

**Comment by RicoSuter** [comment]
I think in this test code NRT is not enabled, right? At least it's not enabled for the whole project (in csproj)

**Comment by ProductiveRage** [comment]
I added my test to one of your classes where it seemed most appropriate: [ObjectExtensionsTests.cs](https://github.com/RicoSuter/Namotion.Reflection/blob/bbecba824e93cd4ba1da0d84fabcab210bc11a4b/src/Namotion.Reflection.Tests/ObjectExtensionsTests.cs#L5)

You can see that it has the line

`
#nullable enable
`

at the top of it.

**Comment by RicoSuter** [comment]
Ah yes, sorry. Will check soon.

**Comment by RicoSuter** [comment]
I think i know the problem: You use a private class for which the attributes are not generated. Quickly try public class to verify.

**Comment by ProductiveRage** [comment]
I've tried changing it from a nested private class to a nested public class. The unit test that I added still does not pass. I've pushed the change to this PR to illustrate.

**Comment by RicoSuter** [comment]
Just looking into it.

**Comment by RicoSuter** [comment]
Ok the problem is that it's a nested class. Just looking for a fix.

**Comment by RicoSuter** [comment]
Fixed with a commit. Can we merge or do you want to change something?

**Comment by RicoSuter** [comment]
Switched to private and this also works now.

**Comment by ProductiveRage** [comment]
The nested class problem sounds like what I reported in issue #25?

I initially wrote this unit test using a private nested class because that is how I would normally write a unit test (or any other code) - keeping accessibility of any classes as restricted as possible.

Perhaps, in retrospect, I should have written the test using a non-nested class to ensure that that did not cloud the issue somehow. With that in mind, I've pushed another commit to this PR that makes the "PersonDetails" class no longer nested. The test still fails.

**Comment by RicoSuter** [comment]
I'm confused - i don't see a commit. 
But i updated your PR and now (19:19 :-)) it looks fine. 
What do you think?

**Comment by RicoSuter** [comment]
I also fixed the CI build in this PR.

**Comment by ProductiveRage** [comment]
> I'm confused - i don't see a commit.
> But i updated your PR and now (19:19 :-)) it looks fine.
> What do you think?

Sorry about this, I pushed and then [alt]-[tabbed] away and didn't realise that there was a fetch that I needed to do. I'm just merging now.

**Comment by RicoSuter** [comment]
I already had a test with a nested class and it also failed. Probably it worked because i used a preview compiler

**Comment by ProductiveRage** [comment]
> I already had a test with a nested class and it also failed. Probably it worked because i used an old preview compiler

That's interesting to know!

I added a couple more unit tests to this PR, just to convince myself that nested classes worked whether they were public or private (and that my original problem, described in issue #24, that didn't have any nested classes was also fixed).

These changes have also fixed the problem in issue #25 - so you should be able to close both issues after this PR is merged.

**Comment by RicoSuter** [comment]
Still green, can we merge?

**Comment by ProductiveRage** [comment]
Yes, please!

**Pull request merged**
