### PR TITLE
fixed output for generic value types

### PR DESCRIPTION
**Pull request by adamjones1**
This looks like it does the trick for #19

### CODE REVIEW

**Comment by RicoSuter** [comment]
I hope this doesnt introduce regressions.

**Comment by adamjones1** [comment]
I don't believe it should - my thinking is that:
1) The tests still all pass
2) The library didn't work in presence of structs with multiple type parameters anyway, and both the changes in the PR easily reduce to the logic used before the PR when such structs are absent. So for the use cases which worked previously, they should still behave the exact same way.

**Comment by RicoSuter** [comment]
You need this in NJsonSchema/NSwag, right?

**Comment by adamjones1** [comment]
Nope, I actually plan to use this lib directly from an app 😃

**Comment by RicoSuter** [comment]
Ok, then update should be available on nuget soon.

**Pull request merged**
