### PR TITLE
Unit tests to illustrate issue #39

### PR DESCRIPTION
**Pull request by ProductiveRage**
Tests created to try to explain myself better in relation to issue #39 (and to offer some regression tests as well as failure cases).

### CODE REVIEW

**Comment by RicoSuter** [comment]
I've fixed the tests - I commented one out as I think there is no way to support that (the information is just not available via reflection). What do you think?

**Comment by ProductiveRage** [comment]
I think that it's a mistake to comment out the test because it's a valid use case. Unfortunately, you are correct that the information does not appear to be available in meta data via the normal forms of reflection but it _is_ in there - I have just struggled so far to get it out!

It might be interesting to know that the project [PublicApiGenerator](https://github.com/PublicApiGenerator/PublicApiGenerator) _can_ make the distinction but it uses Mono.Cecil to get the information out. I know that your project here requires zero dependencies, which is very attractive, but it should be feasible to look into the the [Mono.Cecil](https://github.com/jbevain/cecil) library is doing and utilise the same logic. I started looking at this a few weeks ago but I got distracted by other things.

The good news, then, is that this information _is_ available - the bad news is that it's not yet clear how to get it out (though hopefully Cecil's source code can help with that!)

**Comment by RicoSuter** [comment]
Probably in PublicApiGenerator (as well as the NJS/NSwag schema generators) always reflect via property or method (return) parameter where you have this info. Here we only have the runtime type here. Maybe we can get the metadata via generic type on the method...

**Comment by ProductiveRage** [comment]
When I looked into it, I got the distinct impression that the
PublicApiGenerator was also considering only runtime information. There are
some differences in the runtime meta data, I've just struggled to find out
how to read it. I found that if I used ildasm then I could see them but, as
I said, I hadn't worked out how to read them or how Mono.Cecil was able to
(though the answer surely lies in there).

I can try and see if I have any of my notes still available from when I
last looked into this.

**Comment by RicoSuter** [comment]
I merged this for now, the missing test can be fixed later... but as i said i dont know whether this is even possible.

**Pull request merged**
